# Generated by Django 3.2.6 on 2021-10-03 14:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=64)),
                ('phone', models.PositiveIntegerField()),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('shipping_by', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=128)),
                ('details', models.CharField(blank=True, max_length=256, null=True)),
                ('price', models.PositiveIntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_model', models.CharField(max_length=4)),
                ('price', models.PositiveSmallIntegerField(default=600)),
                ('color', models.CharField(choices=[('Бежевый', 'Бежевый'), ('Темно-бежевый', 'Темно-бежевый'), ('Кэмел', 'Кэмел'), ('Фисташковый', 'Фисташковый'), ('Мята', 'Мята'), ('Розовый', 'Розовый'), ('Коррал', 'Коррал'), ('Черный', 'Черный')], max_length=16)),
                ('size', models.CharField(default='XXS, XS, S, M, L, XL', max_length=32)),
                ('fabric_structure', models.CharField(blank=True, default='80% cotton, 20% poly', max_length=40, verbose_name='Состав ткани')),
                ('description', models.TextField()),
                ('sale', models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(600)], verbose_name='Цена со скидкой')),
                ('picture', models.ImageField(upload_to='products', verbose_name='Главная картинка')),
                ('picture2', models.ImageField(blank=True, null=True, upload_to='products')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='OrderItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ordermodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productmodel')),
            ],
            options={
                'verbose_name': 'Заказанный товар',
                'verbose_name_plural': 'Заказанные товары',
            },
        ),
        migrations.CreateModel(
            name='OneClickOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.PositiveSmallIntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productmodel')),
            ],
            options={
                'verbose_name': 'OneClick Заказ',
                'verbose_name_plural': 'OneClick Заказы',
            },
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64)),
                ('product_id', models.PositiveIntegerField()),
                ('size', models.CharField(default='XXX', max_length=3)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзина',
            },
        ),
    ]
