# Generated by Django 3.1.2 on 2020-10-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201024_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='fabric_structure',
            field=models.CharField(blank=True, default='80% cotton, 20% poly', max_length=40, verbose_name='Состав ткани'),
        ),
    ]
