# Generated by Django 3.1.2 on 2020-10-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_productmodel_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='picture',
            field=models.ImageField(null=True, upload_to='products', verbose_name='Главная картинка'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.DeleteModel(
            name='ImagesModel',
        ),
    ]
