# Generated by Django 3.1.2 on 2020-10-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201024_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='sale',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, null=True, verbose_name='Цена со скидкой'),
        ),
    ]
