# Generated by Django 3.1.2 on 2020-10-26 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201026_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, default=600),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='sale',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(600)], verbose_name='Цена со скидкой'),
        ),
    ]
