# Generated by Django 3.1.2 on 2020-10-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201026_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='color',
            field=models.CharField(choices=[('Бежевый', 'Бежевый'), ('Темно-бежевый', 'Темно-бежевый'), ('Кэмел', 'Кэмел'), ('Фисташковый', 'Фисташковый'), ('Мята', 'Мята'), ('Розовый', 'Розовый'), ('Коррал', 'Коррал'), ('Черный', 'Черный')], max_length=13),
        ),
    ]
