# Generated by Django 3.1.2 on 2020-10-30 20:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_oneclickordermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneclickordermodel',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
