# Generated by Django 3.1.2 on 2020-10-31 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201030_2244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oneclickordermodel',
            options={'verbose_name': 'OneClick Заказ', 'verbose_name_plural': 'OneClick Заказы'},
        ),
    ]
