# Generated by Django 3.1.2 on 2020-10-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201031_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='oneclickordermodel',
            name='size',
            field=models.CharField(default='XXX', max_length=3),
        ),
    ]
