# Generated by Django 3.1.2 on 2020-10-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_oneclickordermodel_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oneclickordermodel',
            name='size',
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='size',
            field=models.CharField(default='XXX', max_length=3),
        ),
    ]
