# Generated by Django 3.1.2 on 2020-11-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20201101_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemsmodel',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
