# Generated by Django 3.1.2 on 2020-11-01 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20201101_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitemsmodel',
            options={'verbose_name': 'Заказанный товар', 'verbose_name_plural': 'Заказанные товары'},
        ),
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
